name: "Snyk Container Image Scan"

on:
  push:
    branches:
      - 'demo*'

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/container-test@v1
        with:
          orgId: 08dddbd0-3c6b-48ec-9e0a-cbd736b0e769
          imageName: defenderk/docker-goof-ci:latest
          file: dockerfiles/Dockerfile
          platform: linux/amd64
          token: ${{ secrets.SNYK_TOKEN }}
