name: "Snyk Container Image Scan"

on:
  push:
    branches:
      - 'demo*'  # Include any branch starting with demo

jobs:
  snyk-scan:
    name: "Snyk Scan Steps"
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Install Snyk
        run: |
          npm install -g snyk

      - name: Authenticate to Snyk
        run: |
          snyk auth ${SNYK_TOKEN}

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker buildx build -f dockerfiles/Dockerfile . -t defenderk/docker-goof-ci:latest
          
      - name: Snyk Image Test
        run: |
          snyk container test defenderk/docker-goof-ci:latest --org 08dddbd0-3c6b-48ec-9e0a-cbd736b0e769 --file=dockerfiles/Dockerfile
          snyk container monitor defenderk/docker-goof-ci:latest --org 08dddbd0-3c6b-48ec-9e0a-cbd736b0e769 --file=dockerfiles/Dockerfile 

      - name: Fail the workflow if Snyk finds vulnerabilities
        run: |
          if [ -n "$(snyk container test defenderk/docker-goof-ci:latest --org 08dddbd0-3c6b-48ec-9e0a-cbd736b0e769 --json)" ]; then
            exit 1
          fi
